import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/common/Header";
import Footer from "./common/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
       <div className="px-3">{children}</div> 
        <Footer/>
      </body>
    </html>
  );
}
